/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;


/**
 *
 * @author Nick
 */
public class GameLoopScene extends Scene {
    private GUI_STATE internalStateTransitionSignal = GUI_STATE.GAMELOOP;
    @Override
    public void setUsername(String name){
        this.jLabel7.setText(name);
    }
    @Override
    public void setTurnCount(int turn){
        this.jLabel1.setText("" + turn);
    }
    @Override
    public void ResetTransition(){
        this.internalStateTransitionSignal = GUI_STATE.GAMELOOP;
    }
    private int prevPlayerId;
    public void setTurn(int playerId){
        switch(this.prevPlayerId){//reset previous player
            case 0:
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
                break;
            case 1:
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
                break;
            case 2:
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
                break;
            case 3:
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
                break;
        }
        switch(playerId){
            case 0:
                jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/activeUser.png")));
                break;
            case 1:
                jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/activeUser.png")));
                break;
            case 2:
                jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/activeUser.png")));
                break;
            case 3:
                jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/activeUser.png")));
                break;
        }
        this.prevPlayerId = playerId;
    }
    @Override
    public GUI_STATE getTransition(){
        return this.internalStateTransitionSignal;
    }
    /**
     * Creates new form GameLoopScene
     */
    
    public GameLoopScene() {
        initComponents();
        this.prevPlayerId = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
        jLabel4.setText("Eliza");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
        jLabel6.setText("Erin");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));

        jButton1.setLabel("Save Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(701, 0, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 33, 37, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/vecteezy_user-profile-icon-profile-avatar-user-icon-male-icon_20911737.png"))); // NOI18N
        jLabel8.setText("Jeff");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/Card Deck - Top Down 88x140.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/background.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel2.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameLoopScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameLoopScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameLoopScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameLoopScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameLoopScene().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
