/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import java.io.File;

/**
 * Represents the home menu scene of the application.
 * <p>This scene serves as the main menu where the user can either start a new game or resume a previously saved game.
 * The user is presented with buttons for starting a new game or resuming an existing game (if a saved game file is found).</p>
 * 
 * @author Nick
 */
public class HomeMenuScene extends Scene {
    /** internal state manager to check if the game should change to another menu*/
    private GUI_STATE internalStateTransitionSignal = GUI_STATE.HOME_MENU;
    
    /**
     * Returns the current transition state of the scene.
     * 
     * @return The transition state of the scene, which is {@link GUI_STATE#HOME_MENU} by default.
     */
    @Override
    public GUI_STATE getTransition(){
        return this.internalStateTransitionSignal;
    }
    
    /**
     * Resets the transition state to the home menu.
     */
    @Override
    public void ResetTransition(){
        this.internalStateTransitionSignal = GUI_STATE.HOME_MENU;
    }
    /**
     * Creates new form HomeMenuScene
     */
    public HomeMenuScene() {
        initComponents();
        this.resumeGame = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Play");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Poker 321");

        jButton3.setText("Resume Game");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private boolean resumeGame;
    
    /**
     * Returns whether the user wants to resume a previously saved game.
     * 
     * @return {@code true} if the user wants to resume a game, otherwise {@code false}.
     */
    public boolean getResumeGame(){
        return this.resumeGame;
    }
    
    /**
     * Handles the action of the "Play" button, which starts a new game. It sets
     * the transition signal to {@link GUI_STATE#PREPLAY_SETTINGS}.
     *
     * @param evt The event that triggered the action.
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.internalStateTransitionSignal = GUI_STATE.PREPLAY_SETTINGS;
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private final String filePath = "resumeGameSave.json";
    
    /**
     * Handles the action of the "Resume Game" button, which checks if a saved
     * game exists. If a saved game file is found, it sets the transition signal
     * to {@link GUI_STATE#GAMELOOP} and sets the {@code resumeGame} flag to
     * {@code true}. If no saved game is found, the button does nothing.
     *
     * @param evt The event that triggered the action.
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        File file = new File(this.filePath);
        if(file.exists()){
            // SEND SIGNAL TO RESUME A GAME
            this.resumeGame = true;
            this.internalStateTransitionSignal = GUI_STATE.GAMELOOP;
        }
        // Does nothing if there is no game to resume
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeMenuScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeMenuScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeMenuScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeMenuScene.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeMenuScene().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
